/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#d4d4db",
        "on-error": "#fff7f6",
        "surface-container-highest": "#e4e2e5",
        "surface-dim": "#dbd9dd",
        "on-tertiary-fixed-variant": "#5b5672",
        "on-secondary-fixed-variant": "#5a5b61",
        "surface-tint": "#5a5e6c",
        "on-background": "#323235",
        "error-dim": "#4e0309",
        "secondary-container": "#e2e2e9",
        "primary-fixed-dim": "#d0d4e4",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#605c78",
        "surface-container-high": "#eae7ea",
        "surface-container": "#f0edef",
        "secondary-fixed": "#e2e2e9",
        "background": "#fcf8f9",
        "on-surface-variant": "#5f5f61",
        "surface-variant": "#e4e2e5",
        "on-error-container": "#752121",
        "surface": "#fcf8f9",
        "error": "#9f403d",
        "secondary": "#5e5f65",
        "on-tertiary": "#fcf7ff",
        "on-secondary-fixed": "#3e3f45",
        "inverse-primary": "#eaedfe",
        "tertiary-dim": "#54506b",
        "primary-dim": "#4e5260",
        "on-secondary-container": "#505157",
        "on-secondary": "#f9f8ff",
        "tertiary-fixed-dim": "#d4cdee",
        "secondary-dim": "#525359",
        "primary": "#5a5e6c",
        "on-tertiary-container": "#514d68",
        "on-primary-container": "#4d515f",
        "outline": "#7b7a7d",
        "inverse-surface": "#0e0e0f",
        "tertiary-fixed": "#e3dbfd",
        "inverse-on-surface": "#9e9c9d",
        "primary-fixed": "#dfe2f2",
        "on-primary": "#f7f7ff",
        "outline-variant": "#b3b1b4",
        "on-primary-fixed-variant": "#575b69",
        "primary-container": "#dfe2f2",
        "surface-bright": "#fcf8f9",
        "error-container": "#fe8983",
        "on-tertiary-fixed": "#3e3a54",
        "on-surface": "#323235",
        "on-primary-fixed": "#3b3f4c",
        "tertiary-container": "#e3dbfd",
        "surface-container-low": "#f6f3f4",
        // Additional colors from Screen 4 reference
        "tertiary-fixed-dim-s4": "#ec6337",
        "on-secondary-fixed-variant-s4": "#4555a8",
      },
      borderRadius: {
        DEFAULT: "2px",
        lg: "4px",
        xl: "8px",
        "2xl": "16px",
        "3xl": "24px",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope_700Bold"],
        body: ["Inter_400Regular"],
        label: ["Inter_600SemiBold"],
      },
    },
  },
  plugins: [],
};
